apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  labels:
    app: n8n
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
