apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-admin
  labels:
    app: app-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-admin
  template:
    metadata:
      labels:
        app: app-admin
    spec:
      containers:
      - name: app-admin
        image: 418272767854.dkr.ecr.ap-northeast-1.amazonaws.com/${PREFIX}-app-admin:latest
        ports:
        - containerPort: 80
        env:
        - name: CLOUDFLARE_TEAM_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: app-admin-jwt-config
              key: team-domain
        - name: CLOUDFLARE_AUD
          valueFrom:
            configMapKeyRef:
              name: app-admin-jwt-config
              key: aud
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-admin-jwt-config
data:
  team-domain: "https://sancodellc.cloudflareaccess.com"
  aud: "c14ca1abaab330fc0fc8c2f06e727e61902522d59fcd5797af8af04aeed72738"
