apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage-efs
  labels:
    app: grafana
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
