apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platy
spec:
  ingressClassName: traefik
  rules:
  - host: platy.sancode.dev
    http:
      paths:
      - path: /api/v1
        pathType: Prefix
        backend:
          service:
            name: platy-backend
            port:
              number: 3000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: platy-frontend
            port:
              number: 80
